# Generated by Django 5.1 on 2024-11-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0002_alter_productos_caducidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='id_proveedor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
