# Generated by Django 5.1 on 2024-12-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0003_productos_id_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='codigo',
            new_name='id_producto',
        ),
    ]
