# Generated by Django 5.1 on 2024-12-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='codigo',
            new_name='id_venta',
        ),
    ]
