# Generated by Django 5.1.2 on 2024-11-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('productos', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=10)),
                ('distribucion', models.CharField(max_length=100)),
                ('p_mayoreo', models.CharField(max_length=100)),
                ('certificado', models.CharField(max_length=100)),
            ],
        ),
    ]
