# Generated by Django 5.1 on 2024-11-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('sueldo', models.CharField(max_length=10)),
                ('fecha_ing', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
