# Generated by Django 5.1.2 on 2024-11-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador_app', '0003_rename_cod_coordinador_coordinador_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinador',
            old_name='apellidos',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='coordinador',
            old_name='zona',
            new_name='puesto',
        ),
        migrations.AddField(
            model_name='coordinador',
            name='fecha_ing',
            field=models.DateField(blank=True, null=True),
        ),
    ]
