# Generated by Django 5.1 on 2024-12-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_app', '0003_rename_novedad_catalogo_novedades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogo',
            old_name='codigo',
            new_name='id_catalogo',
        ),
    ]
