# Generated by Django 5.1 on 2024-11-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=10)),
                ('numCuenta', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
    ]
