# Generated by Django 5.1 on 2024-12-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='codigo',
            new_name='id_cliente',
        ),
    ]
