# Generated by Django 5.1 on 2024-12-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0002_rename_codigo_clientes_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
